EmployeeTask/Controllers/EmployeesController.cs
namespace EmployeeTask.Controllers
{
    using System;
    using System.Linq;
    using EmployeeTask.Data;
    using EmployeeTask.Data.Models;
    using EmployeeTask.Models.Employees;
    using Microsoft.AspNetCore.Mvc;    
    using System.Collections.Generic;
    

    public class EmployeesController : Controller
    {

        private readonly EmployeeTaskDbContext data;

        public EmployeesController(EmployeeTaskDbContext data)
        {
            this.data = data;
        }

        
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddEmployeeFormModel employee)
        {
            var employeeToAdd = new Employee
            {
                FirstName = employee.FirstName,
                MiddleName = employee.MiddleName,
                LastName = employee.LastName,
                Email = employee.Email,
                PhoneNumber = employee.PhoneNumber,
                BirthDate = employee.BirthDate,
                Salary = employee.Salary,
            };

            this.data.Add(employeeToAdd);

            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        public IActionResult Delete(int id)
        {
            var employeeDelete = data.Employees.FirstOrDefault(x => x.Id == id);

            data.Employees.Remove(employeeDelete);

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }


        public IActionResult Edit(int id)
        {
            var employeeId = data.Employees.FirstOrDefault(x => x.Id == id);

            var employeeForm = new EditEmployeeFormModel
            {
                FirstName = employeeId.FirstName,
                MiddleName = employeeId.MiddleName,
                LastName = employeeId.LastName,
                Email = employeeId.Email,
                PhoneNumber = employeeId.PhoneNumber,
                BirthDate = employeeId.BirthDate,
                Salary = employeeId.Salary
            };

            return View(employeeForm);
        }

        [HttpPost]
        public IActionResult Edit(int id, EditEmployeeFormModel employeeForm)
        {

            var employeeId = data.Employees.FirstOrDefault(x => x.Id == id);

            employeeId.FirstName = employeeForm.FirstName;
            employeeId.MiddleName = employeeForm.MiddleName;
            employeeId.LastName = employeeForm.LastName;
            employeeId.Email = employeeForm.Email;
            employeeId.PhoneNumber = employeeForm.PhoneNumber;
            employeeId.BirthDate = employeeForm.BirthDate;
            employeeId.Salary = employeeForm.Salary;

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }
    }
}

EmployeeTask/Controllers/Top5Controller.cs
namespace EmployeeTask.Controllers
{
    using EmployeeTask.Data;
    using EmployeeTask.Models.Employees;
    using EmployeeTask.Models.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;

    public class Top5Controller : Controller
    {
        private readonly EmployeeTaskDbContext data;

        public Top5Controller(EmployeeTaskDbContext data)
        {
            this.data = data;
        }


        public IActionResult TakeTop5()
        {
            var employees = data.Employees.Select(x => new AllEmployeesFormModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                MiddleName = x.MiddleName,
                LastName = x.LastName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                BirthDate = x.BirthDate,
                Salary = x.Salary,
                CountCompletedTasks = x.CountCompletedTasks,
                
                Tasks = x.Tasks.Select(p => new TaskModel()
                {
                    Id = p.Id,
                    Title = p.Title,
                    Description = p.Description,
                    DueDate = p.DueDate,
                    IsCompleted = p.IsCompleted,
                }).ToList()
            }).ToList();
           

            var orderedEmployees = employees.OrderByDescending(x => x.CountCompletedTasks).Take(5).ToList();

            return View(orderedEmployees);
        }
    }
}

EmployeeTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">yordanov8801@gmail.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="AllEmployees" asp-action="All">All Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" asp-area="" asp-controller="Top5" asp-action="TakeTop5">Top 5 Employees with the most tasks</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EmployeeTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>