EmployeeTask/Controllers/AllEmployeesController.cs
namespace EmployeeTask.Controllers
{
    using System.Linq;
    using EmployeeTask.Data;
    using EmployeeTask.Data.Models;
    using EmployeeTask.Models.Employees;
    using EmployeeTask.Models.Tasks;
    using Microsoft.AspNetCore.Mvc;
    

    public class AllEmployeesController : Controller
    {
        private readonly EmployeeTaskDbContext data;

        public AllEmployeesController(EmployeeTaskDbContext data)
        {
            this.data = data;
        }


         public IActionResult All()
         {
            var employees = data.Employees.Select(x => new AllEmployeesFormModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                MiddleName = x.MiddleName,
                LastName = x.LastName,
                Email = x.Email,
                PhoneNumber = x.PhoneNumber,
                BirthDate = x.BirthDate,
                Salary = x.Salary,
                Tasks = x.Tasks.Select(p => new TaskModel
                {      
                    Id = p.Id,
                    Title = p.Title,
                    Description = p.Description,
                    DueDate = p.DueDate,
                    IsCompleted = p.IsCompleted,
                }).ToList()   
            }).ToList();
           
            return View(employees);
         }


        public IActionResult AddTask()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult AddTask(int id, AddTaskFormModel task)
        {
            var employee = data.Employees.FirstOrDefault(x => x.Id == id);

            Task newTask = new Task
            {
                Title = task.Title,
                Description= task.Description, 
                Employee = employee,
                DueDate= task.DueDate,
                IsCompleted = false
            };

            employee.Tasks.Add(newTask);

            this.data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }        
    }
}

EmployeeTask/Controllers/EmployeesController.cs
namespace EmployeeTask.Controllers
{
    using System;
    using System.Linq;
    using EmployeeTask.Data;
    using EmployeeTask.Data.Models;
    using EmployeeTask.Models.Employees;
    using Microsoft.AspNetCore.Mvc;    
    using System.Collections.Generic;
    

    public class EmployeesController : Controller
    {

        private readonly EmployeeTaskDbContext data;

        public EmployeesController(EmployeeTaskDbContext data)
        {
            this.data = data;
        }

        
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddEmployeeFormModel employee)
        {
            var employeeToAdd = new Employee
            {
                FirstName = employee.FirstName,
                MiddleName = employee.MiddleName,
                LastName = employee.LastName,
                Email = employee.Email,
                PhoneNumber = employee.PhoneNumber,
                BirthDate = employee.BirthDate,
                Salary = employee.Salary,
            };

            this.data.Add(employeeToAdd);

            this.data.SaveChanges();

            return RedirectToAction("Index", "Home");
        }


        public IActionResult Delete(int id)
        {
            var employeeDelete = data.Employees.FirstOrDefault(x => x.Id == id);

            data.Employees.Remove(employeeDelete);

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }


        public IActionResult Edit(int id)
        {
            var employeeId = data.Employees.FirstOrDefault(x => x.Id == id);

            var employeeForm = new EditEmployeeFormModel
            {
                FirstName = employeeId.FirstName,
                MiddleName = employeeId.MiddleName,
                LastName = employeeId.LastName,
                Email = employeeId.Email,
                PhoneNumber = employeeId.PhoneNumber,
                BirthDate = employeeId.BirthDate,
                Salary = employeeId.Salary
            };

            return View(employeeForm);
        }

        [HttpPost]
        public IActionResult Edit(int id, EditEmployeeFormModel employeeForm)
        {

            var employeeId = data.Employees.FirstOrDefault(x => x.Id == id);

            employeeId.FirstName = employeeForm.FirstName;
            employeeId.MiddleName = employeeForm.MiddleName;
            employeeId.LastName = employeeForm.LastName;
            employeeId.Email = employeeForm.Email;
            employeeId.PhoneNumber = employeeForm.PhoneNumber;
            employeeId.BirthDate = employeeForm.BirthDate;
            employeeId.Salary = employeeForm.Salary;

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }
    }
}

EmployeeTask/Controllers/TasksController.cs
namespace EmployeeTask.Controllers
{
    using EmployeeTask.Data;
    using EmployeeTask.Models.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;

    public class TasksController : Controller
    {

        private readonly EmployeeTaskDbContext data;

        public TasksController(EmployeeTaskDbContext data)
        {
            this.data = data;
        }


        public IActionResult TaskView(int id, int ide)
        {
            var taskId = data.Tasks.FirstOrDefault(x => x.Id == id);
            var employee = data.Employees.FirstOrDefault(x => x.Id == ide);

            var taskForm = new TaskFormModel
            {
                Id = taskId.Id,
                Title = taskId.Title,
                Description = taskId.Description,
                DueDete = taskId.DueDate,
                IsCompleted = taskId.IsCompleted,
                EmployeeId = employee.Id,
            };

            return View(taskForm);
        }


        public IActionResult Delete(int id, int ide)
        {
            var taskDelete = data.Tasks.FirstOrDefault(x => x.Id == id);
            var employee = data.Employees.FirstOrDefault(x => x.Id == ide);

            if (taskDelete.IsCompleted == true)
            {
                employee.CountCompletedTasks--;
            }
            

            data.Tasks.Remove(taskDelete);

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }

        public IActionResult EditTask(int id)
        {
            var task = data.Tasks.FirstOrDefault(x => x.Id == id);

            var taskForm = new EditTaskFormModel
            {
                Title = task.Title,
                Description = task.Description,
                DueDate = task.DueDate,
                IsCompleted = task.IsCompleted
            };

            return View(taskForm);
        }

        [HttpPost]
        public IActionResult EditTask(int id, EditTaskFormModel formModel)
        {

            var task = data.Tasks.FirstOrDefault(x => x.Id == id);

            task.Title = formModel.Title;  
            task.Description = formModel.Description;
            task.DueDate = formModel.DueDate;

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }


        public IActionResult Return()
        {
            return RedirectToAction("All", "AllEmployees");
        }


        public IActionResult Complete(int id, int ide)
        {
            var task = data.Tasks.FirstOrDefault(x => x.Id == id);
            var employee = data.Employees.FirstOrDefault(x => x.Id == ide);

            employee.CountCompletedTasks++;
            task.IsCompleted = true;


            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }

        public IActionResult Restart(int id, int ide)
        {
            var task = data.Tasks.FirstOrDefault(x => x.Id == id);
            var employee = data.Employees.FirstOrDefault(x => x.Id == ide);

            employee.CountCompletedTasks--;
            task.IsCompleted = false;

            data.SaveChanges();

            return RedirectToAction("All", "AllEmployees");
        }
    }
}

EmployeeTask/Views/AllEmployees/AddTask.cshtml
@model AddTaskFormModel

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <h2 class="heading-margin text-center text-danger">Add Task</h2>
            <h3 class="heading-margin text-center text-danger">-----------------------------------------------</h3>
            
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title ....">
            </div>
            <div class="form-group"> 
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" placeholder="Description ....">
            </div>
            <div class="form-group"> 
                <label asp-for="DueDate"></label>
                <input asp-for="DueDate" class="form-control" placeholder="00.00.0000 ....">
            </div>
                                  
            <div class="mb-5"></div>

            <input class="btn btn-outline-success col-md-12" type="submit" value="Save" />
        </form>
    </div>
</div>

EmployeeTask/Views/AllEmployees/All.cshtml
@model List<AllEmployeesFormModel>

<div class="mb-5"></div>

<h1 class="text-center">All Employees</h1>

<div class="mb-4"></div>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">FirstName</th>
      <th scope="col">MiddleName</th>
      <th scope="col">LastName</th>
      <th scope="col">Email</th>
      <th scope="col">PhoneNumber</th>
      <th scope="col">BirthDate</th>
      <th scope="col">Salary</th>
      <th scope="col">Operations</th>
      <th scope="col">Tasks</th>
    </tr>
  </thead>
  <tbody>
     
    @foreach (var employee in Model)
   {
     var tasks = employee.Tasks;
        
     <tr>
        <td scope="col">@employee.FirstName</td>
        <td scope="col">@employee.MiddleName</td>
        <td scope="col">@employee.LastName</td>
        <td scope="col">@employee.Email</td>
        <td scope="col">@employee.PhoneNumber</td>
        <td scope="col">@employee.BirthDate.ToString("dd/MM/yyyy")</td>
        <td scope="col">@(employee.Salary)</td>
        
        <td scope="col">                                   
            <a asp-area="" asp-controller="Employees" asp-action="Delete" asp-route-id="@employee.Id" class="btn btn-danger float-left ml-3">Delete</a>             
            <a asp-area="" asp-controller="Employees" asp-action="Edit" asp-route-id="@employee.Id" class="btn btn-warning float-left ml-3">Edit</a>            
            <a asp-area="" asp-controller="AllEmployees" asp-action="AddTask" asp-route-id="@employee.Id" class="btn btn-info float-left ml-3">AddTask</a>               
        </td> 

        <td scope="col">               
              @foreach(var task in tasks)
              {
                        @if (task.IsCompleted == false)
                        {
                            <a asp-area="" asp-controller="Tasks" asp-action="TaskView" asp-route-id="@task.Id" asp-route-ide="@employee.Id"class="btn btn-danger float-left ml-3">@task.Title</a>                            
                        }

                        @if(task.IsCompleted == true)
                        {
                            <a asp-area="" asp-controller="Tasks" asp-action="TaskView" asp-route-id="@task.Id" asp-route-ide="@employee.Id"class="btn btn-success float-left ml-3">@task.Title</a>
                        }                                                          
              }
        </td>                   
     </tr>                  
   }
  </tbody>
</table>